# Site settings
title: English Camp
description: "Thinker // Designer // Youtuber"
email: artist@email

avatar: face1.jpg


# Build settings
markdown: kramdown
permalink: pretty

port: 4000

sass:
  sass_dir: assets/css
  style: :compressed