# Site settings
title: Data Analysts cant cook
description: "Just a list of recipees for <strong>@username</strong> not to forget"
email: artist@email

avatar: face1.jpg


# Build settings
markdown: kramdown
permalink: pretty

port: 4000

sass:
  sass_dir: assets/css
  style: :compressed